### ISSUE TITLE
missing  'get_symbols'

### ISSUE THREAD

**Issue by ramphkg** [jackmoody11/stockscore#99]
Traceback (most recent call last):
  File "stockscore.py", line 7, in <module>
    from stockscore.data import get_symbols
ImportError: cannot import name 'get_symbols'

**Comment by brandonscript** [comment]
Looking at this, I'm confused what it was even supposed to do? That method doesn't exist in the codebase at all.

**Comment by asafravid** [comment]
I'm also getting this error:
```
"C:\Program Files (x86)\Python37-32\python.exe" C:/Users/Asaf/Documents/GitHub/stockscore/stockscore.py
Traceback (most recent call last):
  File ".../stockscore/stockscore.py", line 7, in <module>
    from stockscore.data import get_symbols
ImportError: cannot import name 'get_symbols' from 'stockscore.data' (...\stockscore\stockscore\data.py)

Process finished with exit code 1

```

**Comment by caiovt** [comment]
I had the same error here. Can anyone help me?

**Comment by dkubanyi** [comment]
It's looking for a collection of symbols it seems, so if you go to stockscore/data.py, and add for example this, it will sort of work:
`def get_symbols():
    return ["AAPL"]
`
However, this isn't the only problem. When the script is then fetching the data, you need an API key for IEX Cloud API, which is not free:
`iexfinance.utils.exceptions.IEXAuthenticationError: The IEX Cloud API key must be provided either through the token variable or through the environmental variable IEX_TOKEN.`
